[package]
name = "crusty-fun-crab"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"

anyhow = "1.0.93"

solana-client = "1.18.2"
solana-sdk = "1.18.2"
spl-associated-token-account = "2.3.0"

tokio = "1.36.0"

anchor-lang = "0.26.0"